### ISSUE TITLE
Timestamps ( Time only )

### ISSUE THREAD

**Issue by DhairyaBahl** [DhairyaBahl/React-Messenger-App#16]
### Description

Devise a method to show the timestamps.

### Suggestion

They should be at the right bottom of the box. which should contain only the time the message was sent ( not the day and date )

### Related Images

As we can see in this whatsapp example. There are timestamps at the end of messages. :thinking: 

![whatsapp](https://user-images.githubusercontent.com/71627983/107198987-d54a2700-6a1b-11eb-8dc6-47c0a68eeb98.jpg)

**Comment by wandering-sage** [comment]
Instead of timestamping the exact time in that msg, it would be better to have how old that certain msg was.
For eg. 
the msg box will say 3 hrs ago or 4 days ago
like in youtube comments
![Capture](https://user-images.githubusercontent.com/61676848/107216283-907dba80-6a32-11eb-98e4-08fb5d93a7a8.PNG)

**Comment by DhairyaBahl** [comment]
@wandering-sage Well ! That's a great Idea :thinking: :fire: . Thanks for the suggestion :heart: .

**Comment by wandering-sage** [comment]
do you have discord or some other way of contact?
I have made some changes to your project
There were 2 errors, removed them

![Capture1](https://user-images.githubusercontent.com/61676848/107221730-06395480-6a3a-11eb-9810-8f6aecc894d7.PNG)

**Comment by DhairyaBahl** [comment]
@wandering-sage My discord username and tag is TSMentMUI#2973 . You can add me as friend :smile: .
